### ISSUE TITLE
null

### ISSUE THREAD

**Issue by codexGW** [A3Armory/A3A_A3Wasteland.Altis#40]

**Comment by Gigatek1** [comment]
This happened on a friends server that was running the exact PBO and config I was but when we switch servers mine would work but their server would not. This was a few months ago. I just want to know why. This is only affecting the laser designator.

**Comment by biabock** [comment]
Welcome to the club buddy...
AgentRev's witchcraft ¯\_(ツ)_/¯

**Comment by Gigatek1** [comment]
It cant be AgentRev. Like I said I had this bug on one server I help someone setup but not on my test server. Both running the same PBO and main config. This was a few months ago. I'm mostly curious at this point more then anything.

**Comment by Gigatek1** [comment]
@AgentRev message me.

**Comment by Gigatek1** [comment]
Never mind [found it](https://github.com/A3Armory/A3A_A3Wasteland.Altis/blob/dev/server/antihack/payload.sqf#L226-L246). Looks like he put it in this commit. That's pretty shitty if intentional. I wasted a good part of a day trying to help a player fix it a while back and good part of today. God knows how much time they and others put into it. I guess I was lucky I use the same external payload file and neglected to update it.
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/commit/f7171c03f1fb1416a22cc09b6a8f5ace0079b7e6

**Comment by biabock** [comment]
"If intentional"...
Well done!
for sure many people would be glad if it actually works

**Comment by Gigatek1** [comment]
I just hope that's not a real bug fix I'm removing. We have had some players with ALOT of first aid kits and other default gear after a couple connection errors.
